import './globals.css';

import Layout from './components/Layout';

export const metadata = {
  title: 'Faucet Pay Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
